### ISSUE TITLE
issue errada, delete.

### ISSUE THREAD

**Issue by 58R1K8GTr** [lithg/URL-PATH-FINDER#1]
issue errada, delete por favor.

**Comment by lithg** [comment]
Obrigado pela issue, b16! Realmente, não tinha percebido o requirements.txt porquê usei o pip freeze pra criar no mesmo venv que estava trabalhando em outro projeto, por isso o conflito. Já arrumei o requirements, valeu mesmo! 

PS: O github não deixa deletar issues.
